In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
pd.options.mode.chained_assignment = None  # default='warn'
plt.rcParams['font.family'] = 'Malgun Gothic'
font = {'size': 16}
matplotlib.rc('font', **font)
tqdm.tqdm.pandas()
import gc
import datetime

In [2]:
basedir = './Training/Training5_20220204/cat_col_maps/'

In [3]:
filenames = [f for f in os.listdir(basedir)]
filenames

['구.xlsx',
 '대장구분명.xlsx',
 '동.xlsx',
 '부동산유형.xlsx',
 '브랜드.xlsx',
 '일괄계약.xlsx',
 '지목.xlsx']

In [4]:
cat_cols = [col.replace('.xlsx', '') for col in filenames]
cat_cols

['구', '대장구분명', '동', '부동산유형', '브랜드', '일괄계약', '지목']

In [5]:
coor_df = pd.read_csv('./Prepped Data/연속지적도출처_지번별좌표_본번부번정리_20211222.csv')
print(coor_df.shape)
coor_df.head()

(922318, 12)


시군구명 법정동명  지번_지목   지번 지목            x좌표            y좌표  글자있음    글자  지번만  본번  \
0  강남구  개포동  0-1 가  0-1  가  206331.014484  442028.661953     0  글자없음  0-1   0   
1  강남구  개포동  0-2 가  0-2  가  206254.177141  441986.263641     0  글자없음  0-2   0   
2  강남구  개포동  0-3 가  0-3  가  206174.409344  441932.356344     0  글자없음  0-3   0   
3  강남구  개포동  0-4 가  0-4  가  206631.548237  442577.897175     0  글자없음  0-4   0   
4  강남구  개포동  0-5 가  0-5  가  205243.406000  442547.328000     0  글자없음  0-5   0   

   부번  
0   1  
1   2  
2   3  
3   4  
4   5

In [6]:
test_gu = '은평구'
test_dong = '불광동'
test_bonbun = 480
test_bubun = 230

In [7]:
test_coor_df = coor_df[
    (coor_df['시군구명'] == test_gu)
    &(coor_df['법정동명'] == test_dong)
    &(coor_df['본번'] == test_bonbun)
    &(coor_df['부번'] == test_bubun)
]
print(test_coor_df.shape)
test_coor_df.head()

(1, 12)


시군구명 법정동명     지번_지목       지번 지목            x좌표            y좌표  글자있음  \
768312  은평구  불광동  480-230대  480-230  대  193102.099881  457961.426861     0   

          글자      지번만   본번   부번  
768312  글자없음  480-230  480  230

In [8]:
training_df = pd.read_csv('./Prepped Data/training_data_20220204_2.csv')
print(training_df.shape)
training_df.head()

(2091509, 18)


주소_건축년도  건축년도  전용면적(㎡)   층       x좌표       y좌표  \
0  서울특별시 강남구 개포동 12 1992  1992    33.18   1  2.066072  4.435861   
1  서울특별시 강남구 개포동 12 1992  1992    39.53   5  2.066072  4.435861   
2  서울특별시 강남구 개포동 12 1992  1992    39.53  12  2.066072  4.435861   
3  서울특별시 강남구 개포동 12 1992  1992    49.86  11  2.066072  4.435861   
4  서울특별시 강남구 개포동 12 1992  1992    39.53   4  2.066072  4.435861   

   계약날짜일수_2006년기준  계약날짜기준_건물연식  계약날짜일수_sin  계약날짜일수_cos  부동산유형  브랜드  대장구분명  지목  \
0               2           14    0.034422    0.999407      0    0      0   0   
1               6           14    0.103102    0.994671      0    0      0   0   
2               8           14    0.137279    0.990532      0    0      0   0   
3               8           14    0.137279    0.990532      0    0      0   0   
4               9           14    0.154309    0.988023      0    0      0   0   

   구  동  일괄계약  거래/보증금(만원)  
0  0  0     0       15900  
1  0  0     0       24800  
2  0  0     0       24700  
3  0  0     0       33300  
4  0  0     0       24700

In [9]:
test_df = training_df.head(0)
print(test_df.shape)
test_df.head()

(0, 18)


Empty DataFrame
Columns: [주소_건축년도, 건축년도, 전용면적(㎡), 층, x좌표, y좌표, 계약날짜일수_2006년기준, 계약날짜기준_건물연식, 계약날짜일수_sin, 계약날짜일수_cos, 부동산유형, 브랜드, 대장구분명, 지목, 구, 동, 일괄계약, 거래/보증금(만원)]
Index: []

In [10]:
test_df.loc[0, '주소_건축년도'] = '서울특별시 ' + test_coor_df['시군구명'].iloc[0] + ' ' + test_coor_df['법정동명'].iloc[0] + ' ' +\
str(test_coor_df['본번'].iloc[0]) + '-' + str(test_coor_df['부번'].iloc[0]) + ' 2021'

In [11]:
(pd.to_datetime(datetime.datetime.now()) - pd.to_datetime('2006-01-01')).days

5881

In [12]:
def year_circular_sine_func(x):
    return np.sin(2*np.pi*((x)/365))

def year_circular_cosine_func(x):
    return np.cos(2*np.pi*((x)/365))

In [13]:
filenames

['구.xlsx',
 '대장구분명.xlsx',
 '동.xlsx',
 '부동산유형.xlsx',
 '브랜드.xlsx',
 '일괄계약.xlsx',
 '지목.xlsx']

In [14]:
for file in filenames:
    print(file)
    cat_df = pd.read_excel(basedir + file)
    display(cat_df)

구.xlsx


강남구  강동구  강북구  강서구  관악구  광진구  구로구  금천구  노원구  도봉구  동대문구  동작구  마포구  서대문구  \
0    0    1    2    3    4    5    6    7    8    9    10   11   12    13   

   서초구  성동구  성북구  송파구  양천구  영등포구  용산구  은평구  종로구  중구  중랑구  
0   14   15   16   17   18    19   20   21   22  23   24

대장구분명.xlsx


일반  산
0   0  1

동.xlsx


개포동  논현동  대치동  도곡동  삼성동  세곡동  수서동  신사동  압구정동  역삼동  율현동  일원동  자곡동  청담동  강일동  \
0    0    1    2    3    4    5    6    7     8    9   10   11   12   13   14   

   고덕동  길동  둔촌동  명일동  상일동  성내동  암사동  천호동  미아동  번동  수유동  우이동  가양동  개화동  공항동  \
0   15  16   17   18   19   20   21   22   23  24   25   26   27   28   29   

   내발산동  등촌동  마곡동  방화동  염창동  외발산동  화곡동  남현동  봉천동  신림동  광장동  구의동  군자동  능동  자양동  \
0    30   31   32   33   34    35   36   37   38   39   40   41   42  43   44   

   중곡동  화양동  가리봉동  개봉동  고척동  구로동  궁동  신도림동  오류동  온수동  천왕동  항동  가산동  독산동  시흥동  \
0   45   46    47   48   49   50  51    52   53   54   55  56   57   58   59   

   공릉동  상계동  월계동  중계동  하계동  도봉동  방학동  쌍문동  창동  답십리동  신설동  용두동  이문동  장안동  전농동  \
0   60   61   62   63   64   65   66   67  68    69   70   71   72   73   74   

   제기동  청량리동  회기동  휘경동  노량진동  대방동  동작동  본동  사당동  상도1동  상도동  신대방동  흑석동  공덕동  \
0   75    76   77   78    79   80   81  82   83    84   85    86   87   88   

   구수동  노고산동  당인동  대흥동  도화동  동교동  마포동  망원동  상수동  상암동  서교동  성산동  신공덕동  신수동  \
0   89    90   91   92   93   94   95   96   97   98   99  100   101  102   

   신정동  아현동  연남동  염리동  용강동   중동  창전동  토정동  하중동  합정동  현석동  남가좌동  냉천동  대신동  대현동  \
0  103  104  105  106  107  108  109  110  111  112  113   114  115  116  117   

   미근동  봉원동  북가좌동  북아현동  신촌동  연희동  영천동  옥천동  창천동  천연동  충정로2가  충정로3가   합동  현저동  \
0  118  119   120   121  122  123  124  125  126  127    128    129  130  131   

   홍은동  홍제동  내곡동  반포동  방배동  서초동  신원동  양재동  염곡동  우면동  잠원동  금호동1가  금호동2가  금호동3가  \
0  132  133  134  135  136  137  138  139  140  141  142    143    144    145   

   금호동4가  도선동  마장동  사근동  상왕십리동  성수동1가  성수동2가  송정동  옥수동  용답동  응봉동  하왕십리동  행당동  \
0    146  147  148  149    150    151    152  153  154  155  156    157  158   

   홍익동  길음동  돈암동  동선동1가  동선동2가  동선동3가  동선동4가  동선동5가  동소문동1가  동소문동3가  동소문동4가  \
0  159  160  161    162    163    164    165    166     167     168     169   

   동소문동5가  동소문동6가  동소문동7가  보문동1가  보문동2가  보문동3가  보문동4가  보문동5가  보문동6가  보문동7가  \
0     170     171     172    173    174    175    176    177    178    179   

   삼선동1가  삼선동2가  삼선동3가  삼선동4가  삼선동5가  상월곡동  석관동  성북동  성북동1가  안암동1가  안암동2가  \
0    180    181    182    183    184   185  186  187    188    189    190   

   안암동3가  안암동4가  안암동5가  장위동  정릉동  종암동  하월곡동  가락동  거여동  마천동  문정동  방이동  삼전동  \
0    191    192    193  194  195  196   197  198  199  200  201  202  203   

   석촌동  송파동  신천동  오금동  잠실동  장지동  풍납동   목동  신월동  당산동  당산동1가  당산동2가  당산동3가  \
0  204  205  206  207  208  209  210  211  212  213    214    215    216   

   당산동4가  당산동5가  당산동6가  대림동  도림동  문래동1가  문래동2가  문래동3가  문래동4가  문래동5가  문래동6가  \
0    217    218    219  220  221    222    223    224    225    226    227   

   신길동  양평동1가  양평동2가  양평동3가  양평동4가  양평동5가  양평동6가  여의도동  영등포동  영등포동1가  영등포동2가  \
0  228    229    230    231    232    233    234   235   236     237     238   

   영등포동3가  영등포동4가  영등포동5가  영등포동6가  영등포동7가  영등포동8가  갈월동  남영동  도원동  동빙고동  동자동  \
0     239     240     241     242     243     244  245  246  247   248  249   

   문배동  보광동  산천동  서계동  서빙고동  신계동  신창동  용문동  용산동2가  용산동3가  용산동5가  원효로1가  원효로2가  \
0  250  251  252  253   254  255  256  257    258    259    260    261    262   

   원효로3가  원효로4가  이촌동  이태원동  주성동  청암동  청파동1가  청파동2가  청파동3가  한강로1가  한강로2가  \
0    263    264  265   266  267  268    269    270    271    272    273   

   한강로3가  한남동  효창동  후암동  갈현동  구산동  녹번동  대조동  불광동  수색동  역촌동  응암동  증산동  진관동  \
0    274  275  276  277  278  279  280  281  282  283  284  285  286  287   

   가회동  견지동  경운동   계동  관수동  관철동  교북동  구기동  낙원동  내수동  누상동  누하동  당주동  돈의동  동숭동  \
0  288  289  290  291  292  293  294  295  296  297  298  299  300  301  302   

   명륜1가  명륜2가  명륜3가  명륜4가  무악동  부암동  사직동  삼청동  수송동  숭인동  신교동  신문로1가  신문로2가  \
0   303   304   305   306  307  308  309  310  311  312  313    314    315   

   신영동  안국동  연건동  연지동  옥인동  운니동  원남동  원서동  이화동  익선동  인사동  인의동  적선동  종로1가  창성동  \
0  316  317  318  319  320  321  322  323  324  325  326  327  328   329  330   

   창신동  청운동  체부동  충신동  통의동  통인

부동산유형.xlsx


아파트  오피스텔  연립다세대
0    0     1      2

브랜드.xlsx


기타  현대  삼성  한신  래미안  아이파크  편한세상  아펠바움  아크로  롯데캐슬  더샵  코오롱  SK  힐스테이트  푸르지오  \
0   0   1   2   3    4     5     6     7    8     9  10   11  12     13    14   

   레미안  LG  데시앙  써밋  디에이치  리슈  대방  호반  포레나  중흥  
0   15  16   17  18    19  20  21  22   23  24

일괄계약.xlsx


N  Y
0  0  1

지목.xlsx


대  도  전  공  임  잡  답  차  장  주   종   수   사   창
0  0  1  2  3  4  5  6  7  8  9  10  11  12  13

In [15]:
training_df['계약날짜일수_2006년기준'].describe()

count    2.091509e+06
mean     2.978506e+03
std      1.726680e+03
min      0.000000e+00
25%      1.334000e+03
50%      3.307000e+03
75%      4.394000e+03
max      5.807000e+03
Name: 계약날짜일수_2006년기준, dtype: float64

In [16]:
test_df.loc[0, '건축년도'] = 2021
test_df.loc[0, '전용면적(㎡)'] = 30
test_df.loc[0, 'x좌표'] = test_coor_df['x좌표'].iloc[0] / 100000
test_df.loc[0, 'y좌표'] = test_coor_df['y좌표'].iloc[0] / 100000
test_df.loc[0, '계약날짜일수_2006년기준'] = 5807
test_df.loc[0, '계약날짜기준_건물연식'] = 0
test_df.loc[0, '계약날짜일수_sin'] = year_circular_sine_func(5807)
test_df.loc[0, '계약날짜일수_cos'] = year_circular_cosine_func(5807)
test_df.loc[0, '층'] = 1
test_df.loc[0, '부동산유형'] = '연립다세대'
test_df.loc[0, '브랜드'] = '기타'
test_df.loc[0, '대장구분명'] = '일반'
test_df.loc[0, '지목'] = '대'
test_df.loc[0, '구'] = '은평구'
test_df.loc[0, '동'] = '불광동'
test_df.loc[0, '일괄계약'] = 'Y'

In [17]:
test_df = test_df.drop(columns=['거래/보증금(만원)'])

In [18]:
test_df.head()

주소_건축년도    건축년도  전용면적(㎡)    층       x좌표       y좌표  \
0  서울특별시 은평구 불광동 480-230 2021  2021.0     30.0  1.0  1.931021  4.579614   

   계약날짜일수_2006년기준  계약날짜기준_건물연식  계약날짜일수_sin  계약날짜일수_cos  부동산유형 브랜드 대장구분명 지목  \
0          5807.0          0.0   -0.538005    0.842942  연립다세대  기타    일반  대   

     구    동 일괄계약  
0  은평구  불광동    Y

In [19]:
filenames

['구.xlsx',
 '대장구분명.xlsx',
 '동.xlsx',
 '부동산유형.xlsx',
 '브랜드.xlsx',
 '일괄계약.xlsx',
 '지목.xlsx']

In [20]:
test_mapped_df = test_df.copy()

In [21]:
for file in filenames:
    map_df = pd.read_excel(basedir + file)
    file = file.replace('.xlsx', '')
    print(file)
    
    map_dict = {}
    for i in range(map_df.shape[1]):
        map_dict[map_df.columns[i]] = map_df.iloc[0, i]
    
    test_mapped_df[file] = test_mapped_df[file].map(map_dict)

구
대장구분명
동
부동산유형
브랜드
일괄계약
지목


In [22]:
test_mapped_df

주소_건축년도    건축년도  전용면적(㎡)    층       x좌표       y좌표  \
0  서울특별시 은평구 불광동 480-230 2021  2021.0     30.0  1.0  1.931021  4.579614   

   계약날짜일수_2006년기준  계약날짜기준_건물연식  계약날짜일수_sin  계약날짜일수_cos  부동산유형  브랜드  대장구분명  지목  \
0          5807.0          0.0   -0.538005    0.842942      2    0      0   0   

    구    동  일괄계약  
0  21  282     1

In [23]:
os.listdir('./Training/Training5_20220204/')

['catboost_quantile0125_0',
 'catboost_quantile0125_1',
 'catboost_quantile0125_2',
 'catboost_quantile0125_3',
 'catboost_quantile0125_4',
 'catboost_quantile025_0',
 'catboost_quantile025_1',
 'catboost_quantile025_2',
 'catboost_quantile025_3',
 'catboost_quantile025_4',
 'catboost_quantile05_0',
 'catboost_quantile05_1',
 'catboost_quantile05_2',
 'catboost_quantile05_3',
 'catboost_quantile05_4',
 'catboost_quantile075_0',
 'catboost_quantile075_1',
 'catboost_quantile075_2',
 'catboost_quantile075_3',
 'catboost_quantile075_4',
 'catboost_quantile0875_0',
 'catboost_quantile0875_1',
 'catboost_quantile0875_2',
 'catboost_quantile0875_3',
 'catboost_quantile0875_4',
 'catboost_RMSE_0',
 'catboost_RMSE_1',
 'catboost_RMSE_2',
 'catboost_RMSE_3',
 'catboost_RMSE_4',
 'cat_col_maps']

In [24]:
models = [f for f in os.listdir('./Training/Training5_20220204/') if f.startswith('catboost')]
models

['catboost_quantile0125_0',
 'catboost_quantile0125_1',
 'catboost_quantile0125_2',
 'catboost_quantile0125_3',
 'catboost_quantile0125_4',
 'catboost_quantile025_0',
 'catboost_quantile025_1',
 'catboost_quantile025_2',
 'catboost_quantile025_3',
 'catboost_quantile025_4',
 'catboost_quantile05_0',
 'catboost_quantile05_1',
 'catboost_quantile05_2',
 'catboost_quantile05_3',
 'catboost_quantile05_4',
 'catboost_quantile075_0',
 'catboost_quantile075_1',
 'catboost_quantile075_2',
 'catboost_quantile075_3',
 'catboost_quantile075_4',
 'catboost_quantile0875_0',
 'catboost_quantile0875_1',
 'catboost_quantile0875_2',
 'catboost_quantile0875_3',
 'catboost_quantile0875_4',
 'catboost_RMSE_0',
 'catboost_RMSE_1',
 'catboost_RMSE_2',
 'catboost_RMSE_3',
 'catboost_RMSE_4']

In [25]:
models[-1]

'catboost_RMSE_4'

In [26]:
import catboost

In [27]:
from catboost import CatBoostRegressor

In [28]:
basedir2 = basedir.replace('cat_col_maps/', '')
basedir2

'./Training/Training5_20220204/'

In [29]:
x_test_mapped_df = test_mapped_df.drop(columns=['주소_건축년도'])
print(x_test_mapped_df.shape)
x_test_mapped_df.head()

(1, 16)


건축년도  전용면적(㎡)    층       x좌표       y좌표  계약날짜일수_2006년기준  계약날짜기준_건물연식  \
0  2021.0     30.0  1.0  1.931021  4.579614          5807.0          0.0   

   계약날짜일수_sin  계약날짜일수_cos  부동산유형  브랜드  대장구분명  지목   구    동  일괄계약  
0   -0.538005    0.842942      2    0      0   0  21  282     1

In [30]:
training_df.head()

주소_건축년도  건축년도  전용면적(㎡)   층       x좌표       y좌표  \
0  서울특별시 강남구 개포동 12 1992  1992    33.18   1  2.066072  4.435861   
1  서울특별시 강남구 개포동 12 1992  1992    39.53   5  2.066072  4.435861   
2  서울특별시 강남구 개포동 12 1992  1992    39.53  12  2.066072  4.435861   
3  서울특별시 강남구 개포동 12 1992  1992    49.86  11  2.066072  4.435861   
4  서울특별시 강남구 개포동 12 1992  1992    39.53   4  2.066072  4.435861   

   계약날짜일수_2006년기준  계약날짜기준_건물연식  계약날짜일수_sin  계약날짜일수_cos  부동산유형  브랜드  대장구분명  지목  \
0               2           14    0.034422    0.999407      0    0      0   0   
1               6           14    0.103102    0.994671      0    0      0   0   
2               8           14    0.137279    0.990532      0    0      0   0   
3               8           14    0.137279    0.990532      0    0      0   0   
4               9           14    0.154309    0.988023      0    0      0   0   

   구  동  일괄계약  거래/보증금(만원)  
0  0  0     0       15900  
1  0  0     0       24800  
2  0  0     0       24700  
3  0  0     0       33300  
4  0  0     0       24700

In [31]:
cat_cols = [col.replace('.xlsx', '') for col in filenames]
cat_cols

['구', '대장구분명', '동', '부동산유형', '브랜드', '일괄계약', '지목']

In [32]:
test_pool = catboost.Pool(x_test_mapped_df, cat_features=cat_cols)

In [33]:
models

['catboost_quantile0125_0',
 'catboost_quantile0125_1',
 'catboost_quantile0125_2',
 'catboost_quantile0125_3',
 'catboost_quantile0125_4',
 'catboost_quantile025_0',
 'catboost_quantile025_1',
 'catboost_quantile025_2',
 'catboost_quantile025_3',
 'catboost_quantile025_4',
 'catboost_quantile05_0',
 'catboost_quantile05_1',
 'catboost_quantile05_2',
 'catboost_quantile05_3',
 'catboost_quantile05_4',
 'catboost_quantile075_0',
 'catboost_quantile075_1',
 'catboost_quantile075_2',
 'catboost_quantile075_3',
 'catboost_quantile075_4',
 'catboost_quantile0875_0',
 'catboost_quantile0875_1',
 'catboost_quantile0875_2',
 'catboost_quantile0875_3',
 'catboost_quantile0875_4',
 'catboost_RMSE_0',
 'catboost_RMSE_1',
 'catboost_RMSE_2',
 'catboost_RMSE_3',
 'catboost_RMSE_4']

In [34]:
rmse_models_list = [model for model in models if 'RMSE' in model]
rmse_models_list

['catboost_RMSE_0',
 'catboost_RMSE_1',
 'catboost_RMSE_2',
 'catboost_RMSE_3',
 'catboost_RMSE_4']

In [35]:
models_list = []
for name in rmse_models_list:
    model = CatBoostRegressor().load_model(basedir2 + name)
    models_list.append(model)

In [36]:
preds_list = []
for model in models_list:
    preds = model.predict(test_pool)
    print(preds)
    preds_list.append(preds)

[27620.62084377]
[27207.85154974]
[26303.36040324]
[26449.3922927]
[27621.58627954]


In [37]:
np.mean(preds_list)

27040.56227379825

In [38]:
np.mean(preds_list) /  30

901.3520757932749

In [39]:
quantile05_model_names_list = [model for model in models if 'quantile05' in model]
quantile05_model_names_list

['catboost_quantile05_0',
 'catboost_quantile05_1',
 'catboost_quantile05_2',
 'catboost_quantile05_3',
 'catboost_quantile05_4']

In [40]:
quantile05_models_list = []
for name in quantile05_model_names_list:
    model = CatBoostRegressor().load_model(basedir2 + name)
    quantile05_models_list.append(model)

In [41]:
quantile05_models_list

In [42]:
preds_list = []
for model in quantile05_models_list:
    preds = model.predict(test_pool)
    preds_list.append(preds)

In [43]:
preds_list

[array([25439.0449392]),
 array([26377.80679935]),
 array([24152.35807225]),
 array([24492.28614373]),
 array([24157.70464776])]

In [44]:
np.mean(preds_list)

24923.840120455556

In [45]:
np.mean(preds_list) / 30

830.7946706818518

In [ ]:
quantile075_model_names_list = [model for model in models if 'quantile075' in model]
quantile075_model_names_list

In [ ]:
quantile075_models_list = []
for name in quantile075_model_names_list:
    model = CatBoostRegressor().load_model(basedir2 + name)
    quantile075_models_list.append(model)

In [ ]:
quantile075_models_list

In [ ]:
preds_list = []
for model in quantile075_models_list:
    preds = model.predict(test_pool)
    preds_list.append(preds)

In [ ]:
preds_list

In [ ]:
np.mean(preds_list)

In [ ]:
np.mean(preds_list) / 20

In [ ]:
quantile025_model_names_list = [model for model in models if 'quantile025' in model]
quantile025_model_names_list

In [ ]:
quantile025_models_list = []
for name in quantile025_model_names_list:
    model = CatBoostRegressor().load_model(basedir2 + name)
    quantile025_models_list.append(model)

In [ ]:
quantile075_models_list

In [ ]:
preds_list = []
for model in quantile025_models_list:
    preds = model.predict(test_pool)
    preds_list.append(preds)

In [ ]:
preds_list

In [ ]:
np.mean(preds_list)

In [ ]:
np.mean(preds_list) / 20